import "@/app/globals.css"; // Ensures root path mapping
import "@/app/fanta-2.css"; // Adds the '@' root alias so it loads on /cart
import Head from "./head";
import Link from "next/link";
import Cart from "../components/Cart";
import ProductsProvider from "@/context/ProductContext";

export const metadata = {
  title: "JLV Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head />
      <body>
        {/* 🌟 FIX 1: Move the Provider inside the body to fix SSR & hydration */}
        <ProductsProvider>
          <div id="app">
            <header>
              <div className="header-content">
                <Link href={'/'}>
                  <h1>JLV Store</h1>
                </Link>
              
                <h5 className="mid-text">- Support Veteran Owned Businesses -</h5>
                <Cart />
              </div>
            </header>
            <main>
              {children}
            </main>
            <div className="hr" />
            <footer>
              <div>
                <div className="email-container">
                  <h5>Sign Up for Our Newsletter!</h5>
                  <div className="sign-up">
                    <div> 
                      <input placeholder="Email address..." />
                    </div>
                    <button className="button-card">Subscribe</button>    
                  </div>
                </div>
              </div>  

              <div className="links-container">
                <div>
                  <h5>Company</h5>
                    <Link href={'/'}>Home</Link>
                    {/* 🌟 FIX 2: Fixed casing to lowercase '/cart' to match route directory */}
                    <Link href={'/cart'}>Cart</Link>
                </div>
                <div>
                  <h5>Store</h5>
                    <Link href={'mailto:jlvahai@gmail.com'}>Contact</Link>
                    <Link href={'/FAQ'}>FAQ</Link>
                </div>
                <div>
                  <h5>Support</h5>
                    <Link href={'/Privacy'}>Privacy</Link>
                    <Link href={'/Service'}>Service</Link>
                </div>
              </div>          
              
              <div className="socials">
                <h5>Follow Us</h5>
                <div className="social-links">
                  <a href="https://www.facebook.com/people/Jarom-Vahai/100077081973769/" target="_blank" rel="noopener noreferrer">
                    <i className="fa-brands fa-facebook"></i>
                  </a>
                  <a href="https://www.twitter.com" target="_blank" rel="noopener noreferrer">
                    <i className="fa-brands fa-twitter"></i>
                  </a>
                  <a href="https://www.instagram.com/jlvahai/" target="_blank" rel="noopener noreferrer">
                    <i className="fa-brands fa-instagram"></i>
                  </a>
                </div>
              </div>

              <p>&copy; 2024 JLV Store. All rights reserved.</p>
            </footer>
          </div>
          {/* Keep only one clean portal target at the very bottom of the body */}
          <div id="portal"></div>
        </ProductsProvider>
      </body>
    </html>
  );
}
